# Generated by Django 5.2 on 2025-04-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sepal_width', models.FloatField()),
                ('sepal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('petal_length', models.FloatField()),
                ('specie', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'iris',
            },
        ),
    ]
