# Generated by Django 5.2 on 2025-04-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_iris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irismodel',
            name='asd',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
